---- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --



-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki
-- Imports

require("modules/monitors")
require("modules/programs")
require("modules/autostart")
require("modules/env")
require("modules/decorations")
require("modules/animations")
require("modules/layout")
require("modules/misc")
require("modules/input")
require("modules/binds")
require("modules/windowrules")

