hl.on("hyprland.start", function () 
	-- hl.exec_cmd("awww-daemon")
	hl.exec_cmd("waypaper")
   	hl.exec_cmd("waybar")
	hl.exec_cmd("swaync")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
end)
